version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "3838:3838"
    volumes:
      - ./app:/app  
    image: batch_flex_shinyapp_02:latest
    


